language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - extra-google-m2repository
  - extra-google-google_play_services
  - extra-android-m2repository
before_install:
  - openssl aes-256-cbc -K $encrypted_ce4c4d37511b_key -iv $encrypted_ce4c4d37511b_iv -in env.tar.enc -out ./env/env.tar -d
  - cd /env && tar xvf env.tar
  - echo yes | sdkmanager "build-tools;28.0.0"
  - nvm install 8
  - gem install fastlane --no-rdoc --no-ri --no-document --quiet
  - npm install -g gulp-cli
install:
  - npm install
script: 
- if [ "$TRAVIS_BRANCH" = "master" ]; then gulp set --env=prod; echo "-----------------------PROD ENV-----------------------";  cd android && ./gradlew assemble;  fi
- if [ "$TRAVIS_BRANCH" = "staging" ]; then gulp set --env=staging; echo "-----------------------STAGING ENV-----------------------";  cd android && ./gradlew assemble;  fi
